name: Development Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Login to JFrog Artifactory
        uses: docker/login-action@v1
        with:
          registry: trialnocmuq.jfrog.io
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWD }}

      - name: Build and Push Docker Image to JFROG
        run: |
          IMAGE_NAME="trialnocmuq.jfrog.io/jfrog-docker-image-repo-for-smruti/python-test-app:${{ github.sha }}"
          docker build -t $IMAGE_NAME -f application-code/Dockerfile .
          docker push $IMAGE_NAME

      